# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f3b400642a0894b8ec489f413c40653dd54f93c1beef7f3f3194be11506f3b978ed9f611075ee501a5537bfdc40ab6d3bb7e0b70992e3327e02eadd4338cc07

test:
  secret_key_base: 70021550802e0b2082d60b4633281acbf7ce6934bd056162829714ced762085e869968c90bbd5cf9ce2bc06f84aad50fb217933ebf685e5306da99404067bd4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
